[package]
name = "markdown-editor"
version = "1.0.0"
description = "Markdown Editor desktop app"
edition = "2021"
rust-version = "1.85.0"


[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "gzip", "brotli", "deflate", "json"] }
url = "2"
base64 = "0.22"
