import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';

const workflow = readFileSync(new URL('../.github/workflows/r12-08.yml', import.meta.url), 'utf8');
import { archiveTauriLinuxSchema } from '../scripts/ci/archive-tauri-schema.mjs';
assert.match(workflow, /node scripts\/ci\/archive-tauri-schema\.mjs/);
assert.match(workflow, /git diff --exit-code/);
assert.match(workflow, /test -z "\$\(git ls-files --others --exclude-standard\)"/);
const schema = 'src-tauri/gen/schemas/linux-schema.json';

function fixture(run) {
  const root = mkdtempSync(join(tmpdir(), 'mdr-worktree-'));
  const repo = join(root, 'repo');
  const evidence = join(root, 'evidence');
  mkdirSync(join(repo, 'src-tauri/gen/schemas'), { recursive: true });
  mkdirSync(join(evidence, 'r12-08'), { recursive: true });
  const git = (...args) => execFileSync('git', args, { cwd: repo, stdio: 'pipe' });
  const write = (name, data) => writeFileSync(join(repo, name), data);
  const execute = () => {
    try {
      archiveTauriLinuxSchema(repo, join(evidence, 'r12-08'));
      git('diff', '--check');
      git('diff', '--exit-code');
      if (git('ls-files', '--others', '--exclude-standard').toString().trim()) return { status: 1 };
      return { status: 0 };
    } catch (error) {
      return { status: 1, error };
    }
  };
  try {
    git('init', '-q');
    write('src-tauri/gen/schemas/desktop-schema.json', '{"type":"object"}\n');
    git('add', '.');
    git('-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-qm', 'fixture');
    run({ repo, evidence, git, write, execute });
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

test('R12 validation records a clean pre-build baseline and refuses a pre-existing Linux schema', () => {
  assert.match(workflow, /test -z "\$\(git status --porcelain\)"/);
  assert.match(workflow, /test ! -e src-tauri\/gen\/schemas\/linux-schema\.json/);
});
test('R12 validation preserves a clean workspace when there is no generated Linux schema', () => fixture(({ execute }) => {
  assert.equal(execute().status, 0);
}));
test('R12 validation archives only a newly generated byte-identical Linux schema', () => fixture(({ repo, evidence, write, execute }) => {
  write(schema, '{"type":"object"}\n');
  assert.equal(execute().status, 0);
  assert.equal(existsSync(join(repo, schema)), false);
  assert.equal(readFileSync(join(evidence, 'r12-08/generated-schemas/linux-schema.json'), 'utf8'), '{"type":"object"}\n');
}));
test('R12 validation rejects a different schema without deleting it', () => fixture(({ repo, write, execute }) => {
  write(schema, '{"unexpected":true}\n');
  assert.notEqual(execute().status, 0);
  assert.equal(readFileSync(join(repo, schema), 'utf8'), '{"unexpected":true}\n');
}));
test('R12 validation never removes a tracked schema', () => fixture(({ repo, write, git, execute }) => {
  write(schema, '{"type":"object"}\n');
  git('add', schema);
  assert.notEqual(execute().status, 0);
  assert.equal(existsSync(join(repo, schema)), true);
}));
test('R12 validation still rejects unrelated untracked files and tracked mutations', () => fixture(({ repo, write, execute }) => {
  write('unexpected.txt', 'keep this file');
  assert.notEqual(execute().status, 0);
  assert.equal(readFileSync(join(repo, 'unexpected.txt'), 'utf8'), 'keep this file');
  rmSync(join(repo, 'unexpected.txt'));
  write('src-tauri/gen/schemas/desktop-schema.json', '{"changed":true}\n');
  assert.notEqual(execute().status, 0);
}));
test('R12 validation rejects non-regular schema output', () => fixture(({ repo, execute }) => {
  mkdirSync(join(repo, schema));
  assert.notEqual(execute().status, 0);
  assert.equal(existsSync(join(repo, schema)), true);
}));
