import test from 'node:test';
import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT=resolve(fileURLToPath(new URL('../..',import.meta.url))); const read=path=>readFile(resolve(ROOT,path),'utf8');
const MODULES=['src/features/sidebar/folder-tree/folder-tree-path-policy.js','src/features/sidebar/folder-tree/folder-tree-normalizer.js','src/features/sidebar/folder-tree/folder-tree-state.js','src/features/sidebar/folder-tree/folder-tree-node-view.js','src/features/sidebar/folder-tree/folder-tree-view.js','src/features/sidebar/folder-tree/folder-tree-controller.js','src/features/sidebar/compatibility/classic-folder-tree-controller-port.js'];
function noBrowserGlobals(source){assert.doesNotMatch(source,/(?:^|[=(:,]\s*)window\s*[.[]/m);assert.doesNotMatch(source,/(?:^|[=(:,]\s*)document\s*[.[]/m);assert.doesNotMatch(source,/(?:^|[=(:,]\s*)localStorage\s*[.[]/m);}

test('Atomic 6.9 exposes responsibility-split Folder Tree modules through the Sidebar public entry',async()=>{const index=await read('src/features/sidebar/index.js');for(const symbol of ['createFolderTreeController','createFolderTreeState','createFolderTreeView','createFolderTreeNodeView','normalizeFolderTreeResult','getNativeParentPath','mountClassicFolderTreeControllerPort'])assert.match(index,new RegExp(symbol));for(const path of MODULES)assert.match(await read(path),/Responsibility:/);await assert.rejects(access(resolve(ROOT,'src/sidebar/folder-file-tree.js')));});
test('Atomic 6.9 Folder Tree reads exclusively through injected FilesPort and owns stale/destroy lifecycle',async()=>{const controller=await read('src/features/sidebar/folder-tree/folder-tree-controller.js');assert.match(controller,/files\.listTextTree\(documentPath\)/);assert.match(controller,/requestGeneration/);assert.match(controller,/generation !== requestGeneration/);assert.match(controller,/destroy\(\)/);assert.doesNotMatch(controller,/listTextFileTree|nativeApi|invoke\(|__TAURI__|showDirectoryPicker|FileSystem/);});
test('Atomic 6.9 removes Folder Tree globals and routes classic sync/open through scoped ports',async()=>{const[main,core]=await Promise.all([read('src/main.js'),read('public/app/core.js')]);assert.doesNotMatch(main,/window\.markdownEditorFileTree|window\.openFolderTreeFile|window\.handleNativeDroppedPath/);assert.match(main,/mountClassicFolderTreeControllerPort/);assert.match(main,/documentUiCommandPort\.invoke\('openFolderTreeFile', path\)/);assert.match(core,/markdownEditorFolderTreeControllerPort/);assert.match(core,/coreFolderTreeControllerPort\.syncCurrentDocument/);assert.match(core,/openFolderTreeFile: path => openFolderTreeFile\(path\)/);assert.doesNotMatch(core,/window\.markdownEditorFileTree/);});
test('Atomic 6.9 keeps Folder Tree state, path policy, normalization, view and node-view boundaries separate',async()=>{const[state,pathPolicy,normalizer,view,nodeView,tabController]=await Promise.all([read(MODULES[2]),read(MODULES[0]),read(MODULES[1]),read(MODULES[4]),read(MODULES[3]),read('src/features/sidebar/tabs/sidebar-tab-controller.js')]);assert.match(state,/expandedDirectories/);assert.doesNotMatch(state,/createElement|listTextTree/);assert.doesNotMatch(pathPolicy,/createElement|listTextTree|expandedDirectories/);assert.doesNotMatch(normalizer,/createElement|listTextTree|expandedDirectories/);assert.match(view,/createFolderTreeNodeView/);assert.match(nodeView,/addEventListener\('click'/);assert.doesNotMatch(view,/listTextTree|nativeApi/);assert.doesNotMatch(nodeView,/listTextTree|nativeApi/);assert.doesNotMatch(tabController,/listTextTree|normalizeFolderTreeResult|expandedDirectories/);});
test('Atomic 6.9 production modules have no direct browser-global authority and 6.10 Menu Model is not started',async()=>{for(const path of MODULES)noBrowserGlobals(await read(path));await assert.rejects(access(resolve(ROOT,'src/features/menu/menu-model.js')));});
