import assert from 'node:assert/strict';
import test from 'node:test';
import { createLayoutState, mountClassicLayoutStatePort } from '../../../src/features/layout/index.js';

test('Atomic 6.1 classic LayoutState port forwards the exact canonical state without owning a second copy', () => {
  const host = {};
  const state = createLayoutState();
  const mounted = mountClassicLayoutStatePort(host, state);
  const port = host.markdownEditorLayoutStatePort;
  assert.equal(port, mounted.api);
  assert.equal(Object.keys(host).includes('markdownEditorLayoutStatePort'), false);
  assert.equal(port.sidebarWidth, 248);
  port.sidebarVisible = false;
  port.sidebarWidth = 312;
  port.editorCollapsed = true;
  port.previewCollapsed = false;
  port.editorRatio = 0.61;
  port.compactSplitActive = true;
  port.compactSplitPane = 'preview';
  port.layoutMode = 'preview';
  port.compactShellActive = true;
  port.compactShellInitialized = true;
  port.pageFullscreen = true;
  port.systemFullscreen = true;
  port.isResizing = true;
  port.isSidebarResizing = true;
  port.windowResizeActiveUntil = 44;
  port.windowResizeBurstStartedAt = 11;
  port.windowResizeBurstEvents = 9;
  assert.equal(port.snapshot, state.snapshot);
  assert.equal(state.snapshot.sidebar.visible, false);
  assert.equal(state.snapshot.sidebar.width, 312);
  assert.equal(state.snapshot.split.ratio, 0.61);
  assert.equal(state.snapshot.split.compactPane, 'preview');
  assert.equal(state.snapshot.mode, 'preview');
  assert.equal(state.snapshot.fullscreen.page, true);
  assert.deepEqual(state.snapshot.resize, { splitActive: true, sidebarActive: true, windowActiveUntil: 44, windowBurstStartedAt: 11, windowBurstEvents: 9 });
  assert.equal(port.getCompactShellMaxWidth(false), 860);
  assert.equal(port.getCompactShellMaxWidth(true), 900);
  assert.equal(port.getCompactSplitMaxWidth(false), 720);
  assert.equal(port.getCompactSplitMaxWidth(true), 760);
  assert.equal(port.breakpoints.narrowInteractive.maxWidth, 768);
  assert.equal(port.matchesNarrowInteractive(query => ({ matches: query === '(max-width: 768px)' })), true);
  mounted.destroy();
  mounted.destroy();
  assert.equal(Object.hasOwn(host, 'markdownEditorLayoutStatePort'), false);
  assert.throws(() => port.snapshot, /destroyed/);
  state.destroy();
});

test('classic LayoutState port rejects duplicate mounts and malformed dependencies', () => {
  assert.throws(() => mountClassicLayoutStatePort(null, {}), /target/);
  const host = {};
  assert.throws(() => mountClassicLayoutStatePort(host, {}), /requires setSidebar/);
  const state = createLayoutState();
  const mounted = mountClassicLayoutStatePort(host, state);
  assert.throws(() => mountClassicLayoutStatePort(host, state), /already mounted/);
  mounted.destroy();
  state.destroy();
});
